spring:
  datasource:
    username: root
    password: zzz
    url: jdbc:mysql://localhost:3306/test01?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/templates
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
