spring:
  mail:
    host: smtp.163.com
    username: aisubtitles@163.com
    password: NZAEPEBLMBIZXHSN
    properties.mail.smtp.port:  465
    from:  aisubtitles@163.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test01?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    com.AISubtitles.Server.mapper: debug
server:
  port: 8083

prop:
  upload-folder: ./files
