spring:
  mail:
    host: smtp.qq.com
    username: 705256817@qq.com
    password: graolschvzbhbbge
    properties.mail.smtp.port:  465
    from:  705256817@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/aisub?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/templates
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com.AISubtitles.Server.mapper: debug
server:
  port: 8080
