spring:
  datasource:
    username: root
    password: 1
    url: jdbc:mysql://localhost:3306/test01?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com.AISubtitles.Server.mapper: debug
server:
  port: 8080
